services:
  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:delegated
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SSH_AUTH_SOCK:-doesnotexist}/ssh-agent
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    command: sleep infinity
    networks:
      - appnet
    depends_on:
      - db
      - redis
  
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: mapsuser
      POSTGRES_PASSWORD: mapspass
      POSTGRES_DB: mapsdb
    ports:
      - "5432:5432"
    networks:
      - appnet
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    networks:
      - appnet

networks:
  appnet:

volumes:
  pgdata: